---
abstract: 'define multiple init args with custom processing'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::Fatal: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: MooseX::CustomInitArgs
name: MooseX-CustomInitArgs
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Data::OptList: 0
  Moose: 2.00
  perl: 5.8.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=MooseX-CustomInitArgs
  homepage: https://metacpan.org/release/MooseX-CustomInitArgs
  license: http://dev.perl.org/licenses/
  repository: https://bitbucket.org/tobyink/p5-moosex-custominitargs
version: 0.001
